apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: abubakeradam/motor-chat:v8.2 
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py kafka_consumer
          envFrom:
            - configMapRef:
                name: django-config