# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: django
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: django
#   template:
#     metadata:
#       labels:
#         app: django
#     spec:
#       containers:
#         - name: django
#           image: abubakeradam/motor-chat:v8.2
#           command: ["/bin/sh", "-c"]
#           args:
#             - |
#               python manage.py migrate &&
#               daphne -b 0.0.0.0 -p 8000 project.asgi:application
#           ports:
#             - containerPort: 8000
#           envFrom:
#             - configMapRef:
#                 name: django-config


apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: django
      containers:
        - name: django
          image: abubakeradam/motor-chat:v8.8
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py migrate &&
              daphne -b 0.0.0.0 -p 8000 project.asgi:application
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: django-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: django



    