# apiVersion: v1
# kind: Secret
# metadata:
#   name: django-secret
# type: Opaque
# stringData:
#   SECRET_KEY: your_secret_key

#   POSTGRES_USER: hiquota1996
#   POSTGRES_PASSWORD: hiquota1996


#   env:
#     - name: DB_USER
#       valueFrom:
#         secretKeyRef:
#           name: django-secret
#           key: POSTGRES_USER

#     - name: DB_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: django-secret
#           key: POSTGRES_PASSWORD

#     - name: ADMIN_USERS
#       valueFrom:
#         secretKeyRef:
#           name: django-secret
#           key: POSTGRES_USER

apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: your_secret_key

  POSTGRES_USER: hiquota1996
  POSTGRES_PASSWORD: hiquota1996